### PR TITLE
CI Test improvements, fixes

### LINKED ISSUE #34305: deploy-sourcegraph-docker test failures don't report as CI failures
https://buildkite.com/sourcegraph/deploy-sourcegraph-docker/builds/10580#a2fce70f-215f-4762-bb67-5d37c428e5fd

Both the docker-compose-test and pure-docker-test runs here failed due to errors, but the build was marked as a success.

### PR DESCRIPTION
**Pull request by caugustus-sourcegraph**
This PR fixes a number of issues:
- When a test failed in this repo, it was incorrectly showing as passing
- Adds a timeout to docker-compose up to prevent infinite builds waiting on the migrator to succeed
- Fixes the failing tests by updating references / container counts / unnecessary commands

There is a problem with the pure-docker tests on the customer-replica branch - when I tried to incorporate these changes as a test, I saw failures in the migrator. I'm going to tackle that as a separate followup.

Closes https://github.com/sourcegraph/sourcegraph/issues/34305.

### Checklist

* [ ] Sister [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph) change:
* [ ] All images have a valid tag and SHA256 sum

### Test plan

Builds fail and report messages to Buildkite - see [this failure](https://buildkite.com/sourcegraph/deploy-sourcegraph-docker/builds/11405). CI passes now.

### CODE REVIEW

File: pure-docker/deploy-codeinsights-db.sh [hunk 1]
```diff
@@ -12,10 +12,6 @@ set -e
 VOLUME="$HOME/sourcegraph-docker/codeinsights-db-disk"
 ./ensure-volume.sh $VOLUME 999
 
-# Remove timescaledb from the shared_preload_libraries configuration
```
Comment (caugustus-sourcegraph) [inline pure-docker/deploy-codeinsights-db.sh:15]: This is no longer needed, it was a one-time command added during the Timescale -> Postgres migration.

File: pure-docker/deploy-caddy.sh [hunk 2]
```diff
@@ -32,5 +32,5 @@ docker run --detach \
     -p 0.0.0.0:443:443 \
     -v $VOLUME:/caddy-storage \
     --mount type=bind,source="$(pwd)"/../caddy/builtins/http.Caddyfile,target=/etc/caddy/Caddyfile \
-    index.docker.io/caddy:2.4.6-alpine@sha256:b5a59725783bab0d65803f87028c68dd6611ca6184040bd98b18797cbe26bdd9
+    index.docker.io/caddy:2.5.1-alpine@sha256:6e62b63d4d7a4826f9e93c904a0e5b886a8bea2234b6569e300924282a2e8e6c
```
Comment (caugustus-sourcegraph) [inline pure-docker/deploy-caddy.sh:35]: Missed during https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/828, but no need to patch the release since the default is to use apache instead of caddy.

**Review by kevinwojo — APPROVED** [review]
